import { describe, expect, it } from "vitest";
import { ExportCostsCsvUseCase } from "../../../../../../src/modules/costs/application/use-cases/ExportCostsCsvUseCase";
import { CostsRepository } from "../../../../../../src/modules/costs/domain/CostsRepository";

describe("ExportCostsCsvUseCase", () => {
    it("returns csv generated by the repository", async () => {
        const useCase = new ExportCostsCsvUseCase({
            getSummary: async () => ({
                range: { from: "", to: "" },
                currency: "USD",
                totals: { costUsd: 0, tokensUsed: 0, executions: 0, avgCostPerExecutionUsd: 0 },
                series: [],
            }),
            getByAgent: async () => ({ range: { from: "", to: "" }, items: [] }),
            exportCsv: async () => "agentId,costUsd\nagent-1,1.25\n",
        } satisfies CostsRepository);

        const csv = await useCase.execute({
            tenantId: "default",
            from: new Date("2026-03-01T00:00:00.000Z"),
            to: new Date("2026-03-31T23:59:59.999Z"),
            groupBy: "agent",
        });

        expect(csv).toContain("agent-1,1.25");
    });
});
