import { v4 as uuidv4 } from "uuid";
import { MemoryPolicy } from "./memory";

const DEFAULT_TENANT_ID = "default";

export function createDefaultMemoryPolicies(now = new Date()): MemoryPolicy[] {
    return [
        {
            id: "memory-policy-session-session",
            memoryType: "session",
            scopeType: "session",
            retentionMode: "session",
            ttlDays: 1,
            maxEntries: 20,
            allowAutoPromotion: false,
            allowManualPin: false,
            allowSemanticExtraction: false,
            tenantId: DEFAULT_TENANT_ID,
            createdAt: now,
            updatedAt: now,
        },
        {
            id: "memory-policy-episodic-task",
            memoryType: "episodic",
            scopeType: "task",
            retentionMode: "persistent",
            ttlDays: 30,
            maxEntries: 50,
            allowAutoPromotion: true,
            allowManualPin: true,
            allowSemanticExtraction: true,
            tenantId: DEFAULT_TENANT_ID,
            createdAt: now,
            updatedAt: now,
        },
        {
            id: "memory-policy-episodic-agent",
            memoryType: "episodic",
            scopeType: "agent",
            retentionMode: "persistent",
            ttlDays: 30,
            maxEntries: 50,
            allowAutoPromotion: true,
            allowManualPin: true,
            allowSemanticExtraction: true,
            tenantId: DEFAULT_TENANT_ID,
            createdAt: now,
            updatedAt: now,
        },
        {
            id: "memory-policy-semantic-agent",
            memoryType: "semantic",
            scopeType: "agent",
            retentionMode: "persistent",
            ttlDays: null,
            maxEntries: 100,
            allowAutoPromotion: false,
            allowManualPin: true,
            allowSemanticExtraction: false,
            tenantId: DEFAULT_TENANT_ID,
            createdAt: now,
            updatedAt: now,
        },
        {
            id: "memory-policy-semantic-project",
            memoryType: "semantic",
            scopeType: "project",
            retentionMode: "persistent",
            ttlDays: null,
            maxEntries: 100,
            allowAutoPromotion: false,
            allowManualPin: true,
            allowSemanticExtraction: false,
            tenantId: DEFAULT_TENANT_ID,
            createdAt: now,
            updatedAt: now,
        },
        {
            id: "memory-policy-semantic-user",
            memoryType: "semantic",
            scopeType: "user",
            retentionMode: "persistent",
            ttlDays: null,
            maxEntries: 100,
            allowAutoPromotion: false,
            allowManualPin: true,
            allowSemanticExtraction: false,
            tenantId: DEFAULT_TENANT_ID,
            createdAt: now,
            updatedAt: now,
        },
        {
            id: "memory-policy-semantic-team",
            memoryType: "semantic",
            scopeType: "team",
            retentionMode: "persistent",
            ttlDays: null,
            maxEntries: 100,
            allowAutoPromotion: false,
            allowManualPin: true,
            allowSemanticExtraction: false,
            tenantId: DEFAULT_TENANT_ID,
            createdAt: now,
            updatedAt: now,
        },
    ];
}

export function createMemorySeedTags(kind: string, id: string): string[] {
    return [kind, id, uuidv4().slice(0, 8)];
}
